---
title: "ECOL 620 Lab 9"
author: "Natalie Schmer"
date: "4/6/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
# Presence- only  = pseudo absences 

{
  library(raster)           
  library(reshape2)         
  library(mgcv)             
  library(dismo)  
  library(glmnet)           
  library(MuMIn)            
  library(PresenceAbsence)  
  library(ecospat) 
  library(tidyverse)
  library(sp)
  library(sf)
  library(rgdal)
  library(tidylog)
  library(randomForest)
}
```

# Prep ebird data
```{r}
#set working directory where data were downloaded
setwd("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9")

#subsetting point data

# original 
owl.data <- read.csv(file="/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/zero_fill_data_Athene_cunicularia.csv", header=TRUE)

# Validation 
# make a column for if present or not, select the efforts now too  
# effort area all NA so went with protocol type, filled in stationary as 0 

sort(names(owl.data))
unique(owl.data$protocol_type)

owl.data.effort <- owl.data %>% 
                dplyr::mutate(presence = ifelse(observation_count== 0, 0, 1)) %>% 
                dplyr::select(presence, duration_minutes, protocol_type, effort_distance_km, latitude, longitude) %>% 
                dplyr::mutate(effort_distance_km = ifelse(protocol_type == "Stationary", 0, effort_distance_km))

# take a 20% sample to use as validation  
#0.2 * 34854 = 6971
# Take the sample and index it vs the original dataset 
owl.val <- sample(nrow(owl.data.effort), 6971)
owl.val <- owl.data.effort[owl.val,]

head(owl.data.effort)
table(owl.data.effort$presence) #skewed towards absence 

table(owl.val$presence)

#subset to presence-only / absence-only and get locations
owl.pres <- owl.data.effort[owl.data.effort$presence==1, ]
owl.abs <- owl.data.effort[owl.data.effort$presence==0,]

owl.pres.xy <- as.matrix(owl.pres[,c("longitude","latitude")])
owl.abs.xy <- as.matrix(owl.abs[,c("longitude","latitude")])

#validation data
owl.val.pres <- as.matrix(owl.val[owl.val$presence==1, c("longitude","latitude")])

owl.val.abs <- as.matrix(owl.val[owl.val$presence==0, c("longitude","latitude")])

owl.val.xy <- as.matrix(owl.val[,c("longitude","latitude")])
```

# Other data

```{r}
# These owls use burrows from prarie dogs (gunnison, white-tailed, black tailed) (https://www.audubon.org/field-guide/bird/burrowing-owl) 

#download and merge those? union, and then raterize
# using overall range layer from https://databasin.org/galleries/bff5f0a55cf94b2cbcf203833a03d198/

bt <- st_read("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/prarie_dog_predictors/BTPrairieDog/BTPrairieDogOverallRange12032020.shp")

bt <- bt %>% 
          dplyr::mutate(Species = "Black-Tailed",
                        Range = 1)

gp <- st_read("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/prarie_dog_predictors/GunnPrairieDog/GunnPrairieDogOverallRange12032020.shp")

gp <- gp %>% 
          dplyr::mutate(Species = "Gunnison's",
                        Range = 1)

wt <- st_read("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/prarie_dog_predictors/WTPrairieDog/WTPrairieDogOverallRange12032020.shp")

wt <- wt %>% 
          dplyr::mutate(Species = "White-Tailed",
                        Range = 1)

pdog_ranges <- rbind(bt, gp, wt)


#check 
mapview::mapview(pdog_ranges, zcol = "Range")

owl.pres %>% 
          dplyr::select(latitude, longitude) %>% 
    rename(Latitude = latitude,
           Longitude = longitude) %>% 
  na.omit() %>% 
    sf::st_as_sf(coords = c("Longitude", "Latitude"), crs = 4326) %>% 
mapview::mapview()+
mapview::mapview(pdog_ranges, zcol = "Species")

class(pdog_ranges)

pdog_ranges <- pdog_ranges %>% 
                    mutate(Range = 1) %>% 
                    dplyr::select(geometry, Range)

mapview::mapview(pdog_ranges)

# export as shapefile
st_write(pdog_ranges, paste0("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/prarie_dog_predictors/", "pdog_ranges.shp"))


# read back in 
pdog_ranges <- st_read("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/prarie_dog_predictors/pdog_ranges.shp")

```

# GIS data
```{r}
#viewing GIS data

#covariate maps
{
#elevation layer
elev <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/elevation.tif")

#tree canopy
canopy <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/tree_canopy_percent_2011_low.tif")  

#mean precip (cm)
precip_annual <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/precip_annual_mean.tif")             

#june precip (cm)
precip_june <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/precip_june_mean.tif") 

#land cover
landcover_11 <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/nlcd2011_low.tif")

# impervious
impervious <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/percent_impervious_surface_2011_low.tif")

# annual temp 
temp_annual <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/temp_annual_mean.tif")

# max june temp
maxtemp_june <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/temp_max_june.tif")

# mean june temp
meantemp_june <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/temp_mean_june.tif")

# min june temp
mintemp_june <- raster("/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/eBird_data_and_predictors/predictors/temp_min_june.tif")
}

# reclassify the nlcd raster to be 0 = not habitat and 1 the habitat


#check maps, will they line up? 
compareRaster(elev, canopy)
compareRaster(elev, precip_annual)
compareRaster(elev, precip_june)
compareRaster(elev, landcover_11)
compareRaster(elev, impervious)
compareRaster(elev, temp_annual)
compareRaster(elev, maxtemp_june)
compareRaster(elev, meantemp_june)
compareRaster(elev, mintemp_june)

#convert prarie dog range to a raster
pdog_ranges_raster <- st_transform(pdog_ranges, crs = crs(elev))

pdog_raster <- rasterize(pdog_ranges_raster, elev)

# reclassify raster to be binary: 1 for the range and 0 for not 
summary(pdog_raster@legend)

unique(pdog_raster)

rclass_pdog <- pdog_raster

rclass_pdog[] <- ifelse(pdog_raster[]>1, 1, 0)

plot(rclass_pdog)

compareRaster(elev, rclass_pdog)

unique(rclass_pdog)

rm(pdog_raster)


# reclassify NLCD: want grassland, prairies, farmland open, low developed, barren  

#add names of categories to raster layer
#land_cover <- landcover_11@data@attributes

# For owls, want barren, shrub/ scrub, grassland, pasture, cultivated crops so locations 21, 22, 23, 31, 52, 71, 81, 82

nlcd_11 <- as.factor(landcover_11)

reclass_raster <- nlcd_11

reclass_ids <- as.data.frame(reclass_raster@data@attributes)

values(reclass_raster) <- 0 

# change the covers 
reclass_ids <- reclass_ids %>%
                  mutate(reclass_land = ifelse(ID %in% c(21, 22, 23, 31, 52, 71, 81, 82), "Habitat", "Not Habitat")) %>%
                  mutate(reclass_id = case_when(reclass_land == "Habitat" ~ 1,
          reclass_land == "Not Habitat" ~ 0)) %>%
  mutate(reclass_id = as.numeric(reclass_id)) %>%
                  dplyr::select(ID, reclass = reclass_id)

# make a matrix
reclass_matrix <- as.matrix(reclass_ids)

# new levels df
nlcd.levels <- levels(nlcd_11)[[1]]

# join IDs and new IDs
reclass.mat <- cbind(levels(nlcd_11)[[1]], reclass_matrix)

# Check 
reclass.mat

# Make it into a matrix 
reclass.mat <- as.matrix(reclass.mat)

#only want the original ID and the new ID
reclass.mat <- reclass.mat[,c(1, 3)]
reclass.mat

#check class
class(reclass.mat[,2])


# Reclassify
reclass_raster <- reclassify(nlcd_11, reclass.mat)

# Plot to check 
plot(reclass_raster)

reclass_nlcd <- reclass_raster

rm(nlcd_11, reclass_raster)
#--------

# re-check the rasters
compareRaster(elev, canopy)
compareRaster(elev, precip_annual)
compareRaster(elev, precip_june)
compareRaster(elev, reclass_nlcd)
compareRaster(elev, impervious)
compareRaster(elev, temp_annual)
compareRaster(elev, maxtemp_june)
compareRaster(elev, meantemp_june)
compareRaster(elev, mintemp_june)
compareRaster(elev, rclass_pdog)
```

# Rasterize ebird data

## Duration 
```{r}

sort(names(owl.data.effort))

#extract data
hist(owl.data.effort$duration_minutes)
median(owl.data.effort$duration_minutes)
mean(owl.data.effort$duration_minutes)

#choose mean or median of minutes 
duration_raster <- owl.data.effort %>% 
                    dplyr::select(longitude, latitude, duration_minutes) %>% 
                    mutate(duration_minutes = 30)

# set coords
coordinates(duration_raster) <- ~ longitude + latitude

proj4string(duration_raster) <- "+proj=longlat +datum=WGS84 +no_defs"

plot(duration_raster)

class(duration_raster)

#rasterize
duration_raster_df <- rasterize(duration_raster, elev, "duration_minutes")

duration_raster_df

class(duration_raster_df)

plot(duration_raster_df)

compareRaster(elev, duration_raster_df)

```

## Effort distance 
```{r}
sort(names(owl.data.effort))

hist(owl.data.effort$effort_distance_km)
median(owl.data.effort$effort_distance_km)
mean(owl.data.effort$effort_distance_km)

#extract data
#use mean or median of dist 
effdist_raster <- owl.data.effort %>% 
                    dplyr::select(longitude, latitude, effort_distance_km) %>% 
                    mutate(effort_distance_km = 0.322)

# set coords
coordinates(effdist_raster) <- ~ longitude + latitude

proj4string(effdist_raster) <- "+proj=longlat +datum=WGS84 +no_defs"

plot(effdist_raster)

class(effdist_raster)
effdist_raster
#rasterize
effdist_raster_df <- rasterize(effdist_raster, elev, "effort_distance_km")

effdist_raster_df

class(effdist_raster_df)

plot(effdist_raster_df)

compareRaster(elev, effdist_raster_df)
```

## Protocol type
```{r}
sort(names(owl.data.effort))

#extract data
# reset to binary, if stationary 0 and 1 for traveling 

unique(owl.data.effort$protocol_type)

protocol_raster <- owl.data.effort %>% 
                    dplyr::select(longitude, latitude, protocol_type) %>% 
                    mutate(protocol_code = ifelse(protocol_type == "Stationary", 0, 1)) %>% 
                    select(-protocol_type)

# set coords
coordinates(protocol_raster) <- ~ longitude + latitude

proj4string(protocol_raster) <- "+proj=longlat +datum=WGS84 +no_defs"

plot(protocol_raster)

class(protocol_raster)
protocol_raster

#rasterize
protocol_raster_df <- rasterize(protocol_raster, elev, "protocol_code")

protocol_raster_df

class(protocol_raster_df)

plot(protocol_raster_df)

compareRaster(elev, protocol_raster_df)
```


# Stack the rasters
```{r}

#create raster stack
layers <- stack(elev, canopy, precip_annual, precip_june, reclass_nlcd, impervious, temp_annual, maxtemp_june, meantemp_june, mintemp_june, rclass_pdog, duration_raster_df, effdist_raster_df, protocol_raster_df)

names(layers) <- c("elevation", "canopy", "precip_annual", "precip_june", "reclassified_nlcd", "impervious_cover", "temp_annual", "maxtemp_june", "meantemp_june", "mintemp_june", "prariedog_range", "effort_duration_min", "effort_dist_km", "protocol_type")

#Generate availability/background points using dismo, same number as the validation 
back.xy <- randomPoints(layers, p=owl.pres.xy, n=6971)

#inspect
head(back.xy)

#re-name columns
colnames(back.xy) <- c("longitude", "latitude")

#plot
plot(elev)
points(back.xy) #random sample from the landscape of presence 

#extract GIS data

#extracts values from layers at pres locations
pres.cov <- raster::extract(layers, owl.pres.xy)          

#extracts values from layers at random locations
back.cov <- raster::extract(layers, back.xy)              

#extracts values from layers at validation locations
val.cov <- raster::extract(layers, owl.val.xy)            

#link data, artificially fill in 0 for prarie dog range 
pres.cov <- data.frame(owl.pres.xy, pres.cov, pres=1)

pres.cov <- pres.cov %>% 
              dplyr::mutate(prariedog_range = ifelse(is.na(prariedog_range), 0, prariedog_range))


back.cov <- data.frame(back.xy, back.cov, pres=0)

back.cov <- back.cov %>% 
              dplyr::mutate(prariedog_range = ifelse(is.na(prariedog_range), 0, prariedog_range))

val.cov <- data.frame(owl.val, back.cov)

val.cov <- val.cov%>% 
              dplyr::mutate(prariedog_range = ifelse(is.na(prariedog_range), 0, prariedog_range))


#remove any potential NAs
pres.cov.narm <- pres.cov[complete.cases(pres.cov),]
back.cov.narm <- back.cov[complete.cases(back.cov),]
val.cov.narm <- val.cov[complete.cases(val.cov),]

#bind presence and background points together
sort(names(pres.cov))
sort(names(back.cov))

# link presence with sampled absence
all.cov <- rbind(pres.cov, back.cov)  

#inspect, last col is pres/ absence and the response variable 
head(all.cov)

#filter 
sort(names(all.cov))

# all.cov <- all.cov %>% 
#               dplyr::select(-latitude.1, -longitude.1, -pres.1)

# Need to add in the ebird effort 

# all.cov.effort <- owl.data.effort %>% 
#                     rename(pres = presence) %>% 
# left_join(all.cov, ., by = c("latitude", "longitude", "pres"))

all.cov.effort <- all.cov[complete.cases(all.cov),]
######################################
```

# GLM

## Model and plot
```{r}

all.cov.effort <- all.cov.effort %>%  
                    mutate(protocol_type_f = factor(protocol_type, levels = c(0, 1)))

sort(names(all.cov.effort))


glm.owl.2 <- glm(pres~canopy+effort_duration_min + effort_dist_km + elevation + impervious_cover + maxtemp_june + meantemp_june + mintemp_june + prariedog_range + precip_annual + precip_june + reclassified_nlcd + protocol_type_f + temp_annual, family=binomial(link=logit), data=all.cov.effort)


#create raster stack
layers.glm.2 <- stack(canopy,
                      duration_raster_df, 
                      effdist_raster_df, 
                      elev,
                      impervious,
                      maxtemp_june, 
                      meantemp_june, 
                      mintemp_june,
                      rclass_pdog,
                      precip_annual,
                      precip_june,
                      reclass_nlcd,
                      protocol_raster_df,
                      temp_annual
                    )

# rename same as model names 
names(layers.glm.2) <- c("canopy",
                         "effort_duration_min", 
                         "effort_dist_km", 
                         "elevation", 
                         "impervious_cover",
                         "maxtemp_june", 
                         "meantemp_june", 
                         "mintemp_june",
                         "prariedog_range",
                         "precip_annual",
                         "precip_june",
                         "reclassified_nlcd",
                         "protocol_type_f",
                         "temp_annual")

# How do we get the duration, etc to be raster 
glm.map <- predict(layers.glm.2, glm.owl.2, type="response")

# export this as .tif
writeRaster(glm.map,'glm_surface.tif', overwrite = T)

# replace the raster stack with the dataframe to validate the model 
mapview::mapview(glm.map)


#plot(glm.map, axes=F, box=F, main="GLM")

glm.map.pt <- rasterToPoints(glm.map)

glm.map.df <- as.data.frame(glm.map.pt)
head(glm.map.df)

# put the state of colorado behind 
states <- as.data.frame(state.x77)
states$region <- tolower(rownames(states))
states_map <- map_data("state")
fact_join <- left_join(states_map, states, by = "region")

co <- fact_join %>% 
            dplyr::filter(region == "colorado")

(glm.map.gg <- ggplot(co,  aes(long, lat))+
  geom_polygon(fill = "gray90")+
  geom_tile(glm.map.df, mapping = aes(x, y, fill = layer))+
  scale_fill_viridis_c(limits = c(0, 1), direction = -1)+
  theme_classic(base_size = 16)+
  theme(legend.position = "bottom",
        legend.text = element_text(size = 9))+
  labs(x = "Latitude",
       y = "Longitude",
       fill = "Occurance",
       title = "GLM"))

png(filename = "/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/gg_glm.png", width = 9, height = 8, units = "in", res = 400)

glm.map.gg

dev.off()
summary(glm.owl.2)

#validate NOT WORKING
# glm.map.validation <- stats::predict(owl.val, glm.owl.2, type="response")


# Since validation didn't work, see how well the presence points overlay 
(glm.map.gg.points <- ggplot(co,  aes(long, lat))+
  geom_polygon(fill = "gray90")+
  geom_tile(glm.map.df, mapping = aes(x, y, fill = layer))+
  geom_point(owl.pres, mapping = aes(longitude, latitude))+
  scale_fill_viridis_c(limits = c(0, 1), direction = -1)+
  theme_classic(base_size = 16)+
  theme(legend.position = "bottom",
        legend.text = element_text(size = 9))+
  labs(x = "Latitude",
       y = "Longitude",
       fill = "Occurance",
       title = "GLM"))

png(filename = "/Users/natalieschmer/Desktop/GitHub/ECOL_620/data/data_for_lab9/gg_glm_points.png", width = 9, height = 8, units = "in", res = 400)

glm.map.gg.points

dev.off()

plot()
```







